### ISSUE TITLE
deus-exmd: Downloading preferences

### ISSUE THREAD

**Issue by vhda** [phoronix-test-suite/test-profiles#1]
While I'm creating this issue related with DeusEx MD test profile, I think this should apply to any other other test that downloads preferences files.

1. When overwriting the user's preferences files, please backup original file before starting the test and restore it at the end (preferably, even if ctrl-c is pressed).
2. If the game includes a popup, then the preference to skip that popup should be enabled.
3. While taking 1. into account, why not use 'sed' or even a 'cat >' to modify user's preferences file? This would make the test self-contained and independent of an online file that may change over time completely unrelated with the test's version.

Thanks in advance.

**Comment by michaellarabel** [comment]
If anyone wants to contribute patches to backup preferences if set and then restore after testing, it would be an easy contribution as it's just some basic shell scripting. Though I don't view it as a priority as the user can rather easily reset their own desired preferences in-game if what they were benchmarking isn't what they desire for their gaming experience. It also affects only just a small number of games where they don't have proper command-line switches for controlling settings and thus requires overwriting the preferences files to change the resolution/quality settings.

Using sed to update the preferences would just be a pain and more work. The online file hosting of the preferences is explicitly for PTS. I version each file uploaded and the test profile uses the SHA256 hash anyhow for seeing that the files haven't changed and in the event I upload new preferences, it's then uploaded with a different file name and a new version of the test profile issued. So that hosting of preferences or other test profiles is not actually an issue at all.
