### ISSUE TITLE
dav1d-1.4.0: Chimera AV1 samples are gone

### ISSUE THREAD

**Issue by flx42** [phoronix-test-suite/test-profiles#113]
https://github.com/phoronix-test-suite/test-profiles/blob/master/pts/dav1d-1.4.0/downloads.xml#L35-L48

```
$ wget http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-AV1-8bit-1920x1080-6736kbps.mp4
--2019-11-22 16:15:02--  http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-AV1-8bit-1920x1080-6736kbps.mp4
Resolving download.opencontent.netflix.com.s3.amazonaws.com (download.opencontent.netflix.com.s3.amazonaws.com)... 54.231.98.128
Connecting to download.opencontent.netflix.com.s3.amazonaws.com (download.opencontent.netflix.com.s3.amazonaws.com)|54.231.98.128|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-22 16:15:02 ERROR 404: Not Found.

$ wget http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-AV1-10bit-1920x1080-6191kbps.mp4
--2019-11-22 16:15:04--  http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-AV1-10bit-1920x1080-6191kbps.mp4
Resolving download.opencontent.netflix.com.s3.amazonaws.com (download.opencontent.netflix.com.s3.amazonaws.com)... 54.231.98.128
Connecting to download.opencontent.netflix.com.s3.amazonaws.com (download.opencontent.netflix.com.s3.amazonaws.com)|54.231.98.128|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-11-22 16:15:04 ERROR 404: Not Found.
```

**Comment by michaellarabel** [comment]
If you download the files from:

http://download.opencontent.netflix.com/?prefix=AV1/Chimera/Old/

And place them in ~/.phoronix-test-suite/download-cache/ (or /var/cache/phoronix-test-suite/download-cache/ if running as root) do they then work?

The Netflix mirrors have been stable for a while but from quick check it looks like they recently changed them... But at least from filename comparison, it looks like that directory above has them. In the morning I will confirm otherwise the MD5/SHA256 matches but if you drop the files into the download-cache they should get automatically picked up in the meantime.

**Comment by michaellarabel** [comment]
The files in that directory did match. pts/dav1d-1.4.1 has now been pushed out with those updated locations.

So next time you run `phoronix-test-suite benchmark dav1d` it should pickup the new revision. (Note: depending upon your experience level with PTS, it may take 24~48 hours until PTS organically sees the new test depending upon last run. `phoronix-test-suite openbenchmarking-refresh` will update the cache manually to 'see' the 1.4.1 update.)

So with that update the downloads should be all set.

**Comment by flx42** [comment]
Thanks a lot for the quick fix!

**Comment by flx42** [comment]
Looks like you will also need to fix `libgav1` by the way.

**Comment by michaellarabel** [comment]
Yep that is in the process of being updated as well.

Note if you install PTS to a lot of systems you may want to look at the `phoronix-test-suite make-download-cach` command and the download caching served through a default Phoromatic Server or otherwise can be hosted on a local LAN. But basically there are options for easily allowing LAN-based (and behind firewall) installations of test files. Docs @ http://phoronix-test-suite.com/documentation/ [hence hadn't noticed the 404's right away for these tests thanks to automatic local caching]
