### ISSUE TITLE
pts/mysqlslap

### ISSUE THREAD

**Issue by grooverdan** [phoronix-test-suite/test-profiles#35]
Both mysql_install_db and mysqld_safe should have  --no-defaults as the first argument to prevent any installed mysql configuration file settings taking effect for the test.

minor: 10.3.9 is out too

**Comment by michaellarabel** [comment]
Thanks, this has been fixed in pts/mysqlslap-1.0.4.

In general tests tend not to be updated against minor point release versions of upstream software unless something very pressing has been changed/added in order to retain compatibility (comparability) in the results for the maximum amount of time by users.

**Comment by grooverdan** [comment]
thanks for the fix.
