### ISSUE TITLE
pts/enconde-mp3 -- Issue with power9-fix.patch

### ISSUE THREAD

**Issue by johnjmar** [phoronix-test-suite/test-profiles#36]
Looks like the patch has an issue:
```
lame-3.100/vc_solution/vc9_lame_dshow.vcproj
patching file configure.in
Hunk #1 FAILED at 94.
1 out of 2 hunks FAILED -- saving rejects to file configure.in.rej
checking build system type... powerpc64le-unknown-linux-gnu
```
Diffing my patch vs. `power9-fix.patch` I see the following:
```
1,2c1,2
< --- configure.in.old  2017-08-15 11:16:31.000000000 -0400
< +++ configure.in      2018-09-23 19:41:40.012250933 -0400
---
> --- configure.in      2018-08-02 15:07:41.944163387 -0500
> +++ configure.in.jjm  2018-08-02 15:10:14.318522611 -0500
5c5
<       if test "" = "yes"; then
---
>       if test "${HAVE_GCC}" = "yes"; then
7,9c7,9
< -             GCC_version="` --version | sed -n '1s/^[[^ ]]* (.*) //;s/ .*$//;1p'`"
< +             GCC_version="` --version | head -n1 | awk '{print }' `"
<               case "" in 
---
> -             GCC_version="`${CC} --version | sed -n '1s/^[[^ ]]* (.*) //;s/ .*$//;1p'`"
> +             GCC_version="`${CC} --version | head -n1 | awk '{print $3}' `"
>               case "${GCC_version}" in 
12c12
<                       AC_MSG_RESULT()
---
>                       AC_MSG_RESULT(${GCC_version})
```

**Comment by johnjmar** [comment]
Hello. I was wondering if you have had time to look at this.

**Comment by michaellarabel** [comment]
Apologies for the delay. Will take a look at that patch shortly. This week from Raptor I should be having a Talos II system locally as well that will help in further verifying POWER9 benchmarking behavior.

**Comment by michaellarabel** [comment]
That patch should now be applied cleanly with the pts/encode-mp3-1.7.2 update. The patch previously got mangled due to some variables not being escaped.

**Comment by johnjmar** [comment]
Thank you Michael.
Excellet news; are you getting the Talos system as a loaner?

**Comment by michaellarabel** [comment]
Yes I now have a Raptor Talos II system locally for benchmarking.

**Comment by johnjmar** [comment]
Awesome. What configuration is the Talos system?
If you ever need help running on power I'm available (you can also email me directly, johnjmar@us.ibm.com)

**Comment by michaellarabel** [comment]
Thanks. It's dual 22-core CPUs and currently equipped with 8 x 8GB DDR4-2666 and NVMe storage.

**Comment by x9foo** [comment]
It seems to me that the patch will not have any effect. You are patching `configure.in`. The install script (https://github.com/phoronix-test-suite/test-profiles/blob/master/pts/encode-mp3-1.7.2/install.sh), however, does not call `autoconf`. So it will still use the original unmodified `configure` script.

In fact, I found this while wondering about very bad lame performance when testing with Fedora 29 and gcc-8.2.1. The standard Fedora lame package is about three times faster than the one in the pts test. The problem seems to be that configure fails to recognize the gcc version properly and then later in configure it will silently skip the `--enable-expopt`. That way lame will be compiled without any optimizations. Since this happens without failing the build (or test), I assume that quite a few more test results on openbenchmark.org could be affected.

**Comment by jnettlet** [comment]
Just ran across this issue.  The fix is to either patch configure.in and regenerate configure or just patch configure directly.  The fix is on line 13198 of the configure file.

--0-9*0-9*)
++[0-9]*[0-9]*)

This brings my lame encoding times down from 90 seconds to 16 seconds.
