### ISSUE TITLE
pts/unigine-super-1.0.4 fails installation because of checksum mismatch

### ISSUE THREAD

**Issue by liam-middlebrook** [phoronix-test-suite/test-profiles#37]
I believe that Unigine may have silently changed the files they're hosting at http://sp-assets.unigine.com/d/Unigine_Superposition-1.0.run (which gets redirected to a mirror like `m11-assets.unigine.com`).

The test profile contains the following checksums for Unigine_Superposition-1.0.run:
- MD5: `51f6fd0adf388d180dd3fede476f4b04`
- SHA256: `c46c87b74dae78cfcd6b4cdb14c53077ea3d3c6d88774b67abaa4994295b936d`

However if I manually download the Unigine_Superposition-1.0.run from the link included in the test profile I get:
- MD5: `991127f472facfd3f75a25c968138974`
- SHA256: `ba828e48ae1082dc5734dc584df7e2d91f56e1c48edb9708cd24c42f6e5d8a32`

For reference the internal sums listed within the .run file are:
- CRC: `3004177712`
- MD5: `5f003973696172ef6df518d33e26f149`

**Comment by michaellarabel** [comment]
Thanks, looking into this now. It does look like they have silently changed the binary as on all my local PTS/Phoromatic caches I have a file that matches the checksum of what's in the test profile.

Redownloading the file on a  different connection to verify the checksum behavior and it's not any gunk with their CDN modifying something, etc. Will then update the test profile with the new checksums.

**Comment by michaellarabel** [comment]
I've confirmed the Linux build has changed while the Windows version is still the same. That's now updated in pts/unigine-super-1.0.5.

(As not sure if you are new to PTS, if you ran unigine-super on the system(s) within the past 24 hours you may need to run `phoronix-test-suite openbenchmarking-refresh` for the OB cache to refresh to see the availability of the new test profile rather than waiting for it to expire after a day.)
